site_name: Dynamite Documentation
nav:
    - '1. Home': 'index.md'
    - '2. Getting Started': 'getting-started.md'
    - '3. API Reference': 'api-reference.md'
    - 'F.A.Q': 'faq.md'
theme: readthedocs
